### PR TITLE
Feature/pagination

### PR DESCRIPTION
**Pull request by JoaquinJimenezGarcia**
Added the posibility to paginate elements.

Also, it includes a new ID per each panel which allows the user to request the page size and the current page by the URL.

It has been fixed error mentioned #92

### CODE REVIEW

**Comment by JoaquinJimenezGarcia** [comment]
Hi @diafour !

Is everything ok? Did you have time to check the new changes? I could help you if you need something.

Thank you very much in advance!

**Comment by diafour** [comment]
@JoaquinJimenezGarcia hello! I am stuck with tooltips combining right now. I will test this PR this week.

There is one thing.. I've renamed some panel settings, e.g. `url` is moved to `tooltip.urls` and `usingUrl` is now `tooltip.freezeOnClick` — is it a problem for your setup? Should I make a simple converter in a StatusHeatmapCtrl constructor to support original settings?

**Comment by JoaquinJimenezGarcia** [comment]
Hello @diafour ! Thank you for your comment. It will be awesome if your could make that simple converter.

Thank you very much!

**Comment by JoaquinJimenezGarcia** [comment]
Hi @diafour ! How is it going?

**Comment by Matkill** [comment]
Hello, i have the same issue when i add an url on the status map
image

the extratooltip does not show the link
image

and i have this error in the console when i click on the green status

image

How can i solve this ?

Thanks for your work and your help on that !

**Comment by diafour** [comment]
@JoaquinJimenezGarcia sorry for the long delay reviewing this PR. I've rebased this PR onto master and create a new PR #112  with squashed commit authored by you and make some changes so pagination now works with `bucketMatrix` structure instead of `cardsData`. Thank you for your contribution and efforts!

**Pull request closed without merging**
