### PR TITLE
ref: one codebase for the hover tooltip and the frozen tooltip

### PR DESCRIPTION
**Pull request by diafour**
This PR is a continuation of https://github.com/flant/grafana-statusmap/pull/86. It addresses suggestions in this comment: https://github.com/flant/grafana-statusmap/pull/86#issuecomment-590897065.

1.  Hover tooltip and frozen tooltip display similar content now. What you see on mouseover, is what you get on click. No ambiguity for mobile users.

2. Filtering by index is fixed earlier, in #91. 

3. 'Tooltip' settings pane is reworked, fields are reorganized. It is compatible with the new layout of 'Edit mode' in Grafana 7.

4. Variable names are renamed.
   - `$time` become `${__url_time_range}` without leading `&` — Grafana 7 has this variable.
   - `$series_label` become `${__y_label}`
   - `$series_extra` become `${__value}` and `${__value_N}` similar to 'table' plugin.
   - date formatting implemented with `${__value_date}` and `${__value_N_date}` variables and 'Date format' field.

5. Url section in the tooltip and Help popup is now visible when the light theme is used.

Known issues:

- No indication of a link between the bucket and the frozen tooltip.
- The frozen tooltip has a fixed `left` position. It doesn't follow a bucket on time range refresh and on panel resize.
- If the tooltip is frozen in Edit mode in Grafana 5.4, it then appears in Normal mode. Grafana 6.7 and 7 don't have this problem.

frozen tooltip

### CODE REVIEW

**Comment by diafour** [comment]
> implement migration logic for legacy configuration

That is a simple converter for initial `urls` property as proposed in this comment: https://github.com/flant/grafana-statusmap/pull/93#issuecomment-604013757


@JoaquinJimenezGarcia FYI

**Comment by kevinbin** [comment]
http://10.186.63.4:5709/d/f3OkMhVmk/mysql-dashboard?${__graph_range}&var-target=${__y_label}
redirect to 
http://10.186.63.4:5709/d/f3okmhvmk/mysql-dashboard?orgId=1&$%7B__graph_range%7D&var-target=10.186.63.4:5690

invaild time range

**Comment by diafour** [comment]
@kevinbin does `${__graph_range} works earlier?

It looks that "system" variables are missing, I check this.

**Comment by diafour** [comment]
Oops, I got it. The popup for URL template is not updated. The variable for time range is `${__url_time_range}` — it is named after a similar variable from Grafana 7.

I'll fix the help message.

**Comment by kevinbin** [comment]
Does the variable for time range support in grafana 6.x ?

**Comment by diafour** [comment]
Yes. The plugin sets this variable, so it works in 5.4.x as well.

**Pull request merged**
